### PR TITLE
Fix zipmaker bugs and gaps

### LINKED ISSUE #845: Zipmaker has to `mkdir -p` the destination directory for the zip
Currently the druid-tree directory structure doesn't exist in zip_storage, so we need to put it there. 

Use `zip.file_path` as the basis of the directory info.

Consider using a `before_perform` callback.

### LINKED ISSUE #849: Zip command must start from "inside" the druid tree
Incorrect Example:
```
zip -vr0X -s 10g here.zip spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001
```
Produces structure like:
```
unzip -l here.zip 
Archive:  here.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  04-20-2018 12:06   spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/
        0  04-20-2018 12:06   spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/data/
        0  04-20-2018 12:06   spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/data/content/
   905566  04-20-2018 12:06   spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/data/content/eric-smith-dissertation-augmented.pdf
  1000217  04-20-2018 12:06   spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/data/content/eric-smith-dissertation.pdf
        0  04-20-2018 12:06   spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/data/metadata/
     1325  04-20-2018 12:06   spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/data/metadata/contentMetadata.xml
     3882  04-20-2018 12:06   spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/data/metadata/descMetadata.xml

```
whereas we want just:
```
        0  04-20-2018 12:06   bj102hs9687/v0001/
        0  04-20-2018 12:06   bj102hs9687/v0001/data/
        0  04-20-2018 12:06   bj102hs9687/v0001/data/content/
   905566  04-20-2018 12:06   bj102hs9687/v0001/data/content/eric-smith-dissertation-augmented.pdf
...
```

After all, we don't want the replicated object to hardcode info about what storage root a MOAB lives on.  That isn't object data (just an artifact of our storage at a given moment in time).

### PR DESCRIPTION
**Pull request by atz**
- Move last auxiliary method from zipmaker to DruidVersionZip
- Handles chdir for zip creation
- Handles `mkdir -p` for zip destination directory
- Performs `touch` on existing zip file to prevent premature cleanup

Fix #849
Fix #845

### CODE REVIEW

**Comment by atz** [comment]
Need this to push stage replication further

File: spec/models/druid_version_zip_spec.rb [hunk 1]
```diff
@@ -63,7 +106,7 @@
     let(:zip_path) { '/tmp/bj/102/hs/9687/bj102hs9687.v0001.zip' }
 
     it 'returns zip string to execute for this druid/version' do
-      expect(dvz.zip_command).to eq "zip -vr0X -s 10g #{zip_path} #{moab_version_path}"
+      expect(dvz.zip_command).to eq "zip -vr0X -s 10g #{zip_path} bj102hs9687/v0001"
```
Comment (SaravShah) [inline spec/models/druid_version_zip_spec.rb]: don't need `let(:moab_version_path)` anymore

File: spec/models/druid_version_zip_spec.rb [hunk 2]
```diff
@@ -1,8 +1,7 @@
 require 'rails_helper'
 
 describe DruidVersionZip do
-  subject(:dvz) { described_class.new(druid, version) }
```
Comment (SaravShah) [inline spec/models/druid_version_zip_spec.rb]: why change it to `let`? just wondering

File: spec/models/druid_version_zip_spec.rb (hunk 1 above)
Comment (atz) [reply spec/models/druid_version_zip_spec.rb]: good point!

File: spec/models/druid_version_zip_spec.rb (hunk 2 above)
Comment (atz) [reply spec/models/druid_version_zip_spec.rb]: Because at one point I mock a piece of it, which rubocop-rspec dislikes.

File: spec/models/druid_version_zip_spec.rb (hunk 1 above)
Comment (atz) [reply spec/models/druid_version_zip_spec.rb]: Removed it.

File: app/models/druid_version_zip.rb [hunk 3]
```diff
@@ -10,11 +12,27 @@ def initialize(druid, version)
     @version = version
   end
 
+  # Changes directory so that the storage root (and druid tree) are not part of
+  # the archival directory structure, just the object.
```
Comment (ndushay) [inline app/models/druid_version_zip.rb]: What do you think about adding an example of the directory structure we're going for here?  The comment assumes the reader has the Moab druid-tree layout readily loaded into their human memory.

Also, what do you think about starting the comment "Creates zip for Moab version, but changes ..."  The comment as it stands reads a little orthogonal to the name of the method.

File: spec/models/druid_version_zip_spec.rb [hunk 4]
```diff
@@ -25,6 +24,50 @@
     end
   end
 
+  describe '.create_zip!' do
```
Comment (ndushay) [inline spec/models/druid_version_zip_spec.rb]: it seems we should have tests somewhere that show the directory structure inside the zip is what we want.

And possibly to show that it writes it to the right directory?  (-p option added)

Comment (atz) [reply spec/models/druid_version_zip_spec.rb]: The specs are mainly concerned with the making the zip command what we expect.  They do not intend to test `zip` itself deeply.  While possible, testing one version of `zip` is meager reassurance, given that we have a system anticipating using multiple different versions of `zip` over time (and simultaneously!).  I'll put some work in this direction, but given the flexibility of the interface w/ the system utils, I don't expect to ever make this bulletproof.

Line 38 already does test that the zip is created in the right place, which implies that the necessary directory was created (else it would raise, like it did when we tried to use it in stage).

Comment (atz) [reply spec/models/druid_version_zip_spec.rb]: @ndushay To do this correctly seems like it would require including a gem like `zip`... in test only, used only for one test.  Does that seem worthwhile?

Comment (ndushay) [reply spec/models/druid_version_zip_spec.rb]: I guess what struck me is that the internal directory structure is really importan, so having a test to show it might be a good thing, long term maint-wise.  What if we just shell out to unpack it and then read the unpacked dir with ruby to check the structure is what we expect?

If we start having multiple zip commands, then the zipmaker code will have to accommodate ... so new code then implies additional tests then as well, no?

Comment (atz) [reply spec/models/druid_version_zip_spec.rb]: Yeah, this is what I mentioned to you at close last night, I think I have a workaround (using `unzip -l ...` process return value like `ls`).  Pursuing that. 

We don't intend to have multiple zip **commands**, we expect that over time, the `zip` utility itself will be updated (or differ on how it was compiled on a given OS).

Comment (atz) [reply spec/models/druid_version_zip_spec.rb]: added test of internal structure

File: app/models/druid_version_zip.rb (hunk 3 above)
Comment (atz) [reply app/models/druid_version_zip.rb]: IMO, I'm not assuming the reader knows anything about druid trees.  I'm saying only the object is preserved and no other structure.  

I agree this comment is more about the `chdir` than a description of the method itself, so I'll add a broader description.
