### PR TITLE
inline the logic provided by the resque-lock gem, drop the dependency

### LINKED ISSUE #1726: resque locks should be deleted upon job completion, success or failure
**Describe the bug**

Based on testing https://github.com/sul-dlss/shared_configs/pull/1670 and https://github.com/sul-dlss/workflow-server-rails/pull/470 using `create_preassembly_image_spec.rb` in the integration test suite, it appears that pres cat jobs are not cleaning up the locks they create to prevent duplicate jobs from running when a job with a given set of params is already enqueued.  This prevents e.g. `ValidateMoabJob` from being enqueued twice in short succession (because it will decline to enqueue until the prior run's lock expires, which takes an hour).

**User Impact**

Because this prevents running the same job with the same parameters twice in rapid succession, this prevents `ValidateMoabJob` from running on the same druid twice in less than an hour.  If we don't fix this, we can't merge https://github.com/sul-dlss/workflow-server-rails/pull/470 to enable the new `validate-moab` integrity check (see #1691), because then versioning something twice in less than an hour would result in the `validate-moab` step silently hanging.

**Object(s) In This Error State**

some druids that ran into this on stage, that i fixed manually last night (by cleaning up stale resque locks and queuing `ValdiateMoabJob`):
https://argo-stage.stanford.edu/view/druid:bb843md0579
https://argo-stage.stanford.edu/view/druid:ct246zw6526
https://argo-stage.stanford.edu/view/druid:dr564nd1378
https://argo-stage.stanford.edu/view/druid:hg653gq1927
https://argo-stage.stanford.edu/view/kk341tv7892
https://argo-stage.stanford.edu/view/bt821jk7040

Steps to Reproduce, if Known:
* deploy https://github.com/sul-dlss/workflow-server-rails/pull/470
* run create_preassembly_image_spec.rb

**Expected behavior**

The lock that prevents a pres cat job with a specific set of parameters from being enqueued twice at the same time gets cleaned up when said job finishes running.

**Screenshots**

n/a

**Additional context**

We use the resque-lock gem to prevent callers from simultaneously enqueuing multiple instances of the same job before the workers have a chance to pick it up.  resque-lock is supposed to set a mutex value that other workers will respect, but it also has a hook to unset that mutex value when the job finishes, regardless of success, so that the same job with the same parameters can then run again.  It appears that the cleanup isn't happening, and that the lock will always last until its expiry time (1 hour).

This hasn't hasn't been a serious issue for us so far, though Julian did suspect something like this was happening, and I had run into trouble queuing the same checksum validation job repeatedly, even when I didn't attempt to re-queue until after the first run finished.  We did spend a bit of time investigating this, but since the main thing that got us to look at it was Redis memory usage, and since we ended up being comfortable with the amount of memory Redis was using, we ended up dropping it.  

* https://github.com/defunkt/resque-lock/blob/master/lib/resque/plugins/lock.rb#L78
  * https://redis.io/commands/setnx
  * https://redis.io/commands/getset
* https://github.com/resque/resque/blob/master/docs/HOOKS.md
  * https://github.com/resque/resque/blob/7f6b88404dd18698f6f4023e18fdc1ae8318e5e5/test/plugin_test.rb
  * https://github.com/resque/resque/blob/7f6b88404dd18698f6f4023e18fdc1ae8318e5e5/test/job_hooks_test.rb

### PR DESCRIPTION
**Pull request by jmartin-sul**
## Why was this change made?

* wire up lock cleanup so it's actually invoked (fixes https://github.com/sul-dlss/preservation_catalog/issues/1726)
* comments explaining locking behavior and providing necessary license info

closes #1726

## How was this change tested?

- [x] existing unit tests to help detect regressions
- [x] manual testing on stage (by enqueuing multiple copies of the same checksum validation job, some overlapping, some not)
- [x] the infra integration test suite, particularly `create_preassembly_image_spec.rb` (since its failure is what caused me to open #1726)
- [x] i'd like to add a unit test to `application_job_spec.rb` showing that the lock gets cleaned up by the newly inlined code when the job runs successfully
- [x] i'd like to add a unit test to `application_job_spec.rb` showing that the lock gets cleaned up by the newly inlined code even when the job errors out (had a little trouble with this because the error gets raised in the test code when the job is run, which is not what i'd expect for an async job, and not what happens when the job errors IRL)
- [x] a lock timeout related test would be nice
- [ ] a test to address the uncovered conditional that's resulting in the code coverage drop would be nice (to be fair, this is likely a very unusual race condition)

WIP until testing's all sorted out

bonus: have `ObjectsController#validate_moab` return an informative error to the caller in the unlikely event that it can't queue the job.

## Which documentation and/or configurations were updated?

comments in relevant code

### CODE REVIEW

File: app/jobs/application_job.rb [hunk 1]
```diff
@@ -21,16 +20,69 @@ class ApplicationJob < ActiveJob::Base
...
+    # otherwise set the new_expiry_time and ensure that no other worker has
+    # acquired the lock, possibly pushing out the expiry time further
+    # "Atomically sets key to value and returns the old value stored at key." -- https://redis.io/commands/getset
+    key_expires_at = Resque.redis.getset(key, new_expiry_time).to_i
+    if now > key_expires_at
+      Rails.logger.info("acquired lock on #{key} (old lock expired, #{now} > #{key_expires_at})")
+      true
+    else
+      Rails.logger.info("failed to acquired lock on #{key} but updated expiry time to #{new_expiry_time} (#{now} <= #{key_expires_at})")
+      false
```
Comment (jmartin-sul) [inline app/jobs/application_job.rb:75]: this `else` is the only part of the PR that's uncovered by tests, and that coverage deficit is what's failing the build.

maybe i'm missing something, but i think this is a hard case to test for, because it requires that a second worker pick up the lock in between the `get` from Redis on line 60 and the `getset` to Redis on line 69.  i do think this condition is worth covering, though, and i've handled it in the same way as the original resque-lock gem, albeit with a bit more logging detail.  but the logic should be equivalent (or that was the intent).

File: app/jobs/application_job.rb [hunk 2]
```diff
@@ -53,3 +105,35 @@ def zip_info_check!(metadata)
...
+# THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND,
+# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
+# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
+# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
+# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
+# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
+# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+# https://github.com/defunkt/resque-lock/blob/e06fc2bd26f96f4f3fe893caa49c1cd42c0c9423/LICENSE
+#
+# This additional copyright statement applies solely to the code that was taken from resque-lock.
```
Comment (jmartin-sul) [inline app/jobs/application_job.rb:139]: this is the first time i've re-used code in this way, i think, so definitely interested in feedback on whether i got this licensing stuff right.

File: app/jobs/application_job.rb [hunk 3]
```diff
@@ -1,18 +1,17 @@
...
+#
+# @note We abort on lock collision, preventing duplicate Jobs from enqueuing.
+# The key is specified by the `queue_lock_key` class method, by default based on job name
+# and serialized arguments (which works well for druid/version), but can be overridden
+# per job class, if needed.  Locks are stored in Redis w/ expiry dates as integers.
+# @see [redis setnx] https://redis.io/commands/setnx (explains the reasoning behind the pattern)
+#
+# @note The queue locking mechanism was lifted from resque-lock. See end of file for
+# obligatory license info and rationale for inlining the gem's logic.
+# @see [resque-lock] https://github.com/defunkt/resque-lock/blob/e06fc2bd26f96f4f3fe893caa49c1cd42c0c9423/lib/resque/plugins/lock.rb
```
Comment (jmartin-sul) [inline app/jobs/application_job.rb:13]: i renamed some of the original methods for clarity.

File: app/jobs/application_job.rb [hunk 4]
```diff
@@ -21,16 +20,69 @@ class ApplicationJob < ActiveJob::Base
...
+  end
+
+  # @return [String] the key for locking this job/payload combination, e.g. 'lock:MySpecificJob-bt821jk7040;1'
+  def self.queue_lock_key(*args)
+    # Changes in ActiveModel object don't result in new lock (which they do when just calling to_s).
+    queue_lock_args = args.map { |arg| arg.class.method_defined?(:to_global_id) ? arg.to_global_id.to_s : arg }
+    "lock:#{name}-#{queue_lock_args.join(';')}"
+  end
+
+  def self.before_enqueue_lock(*args) # rubocop:disable Metrics/AbcSize
```
Comment (jmartin-sul) [inline app/jobs/application_job.rb:46]: this method contains the trickiest and most important part of the resque-lock logic.  i tried to keep it basically the same as the original in terms of its use of redis and the conditions it checks, but i did rename some variables and add some logging for clarity.

**Comment by jmartin-sul** [comment]
The newly added logging statements are at `info` level right now.  I'm inclined to leave them that way for a few weeks while this is new to prod, and to file a ticket to turn them down to `debug` later.

File: spec/jobs/application_job_spec.rb [hunk 5]
```diff
@@ -2,34 +2,78 @@
...
   it 'queues start empty' do
-    expect(Resque.info).to include(pending: 0)
+    expect(enqueued_jobs.size).to eq 0
   end
 
   context 'a subclass with message(s) queued' do
-    before do
-      allow(ZipmakerJob).to receive(:perform_later).and_call_original # undo rails_helper block
-      ZipmakerJob.perform_later('1234abc', 1)
-    end
```
Comment (jmartin-sul) [inline spec/jobs/application_job_spec.rb:21]: i thought this was clearer inline in the individual tests, and no need to undo zipmaker monkeypatching from rails_helper with the new test class

File: spec/jobs/application_job_spec.rb [hunk 6]
```diff
@@ -2,34 +2,78 @@
...
+      expect { RegularParameterJob.perform_later('4321cba', 1, false) }
+        .to change(enqueued_jobs, :size).from(0).to(1)
+    end
+
+    it 'cleans up its lock after failing so that the same job with the same params can be queued again immediately' do
+      RegularParameterJob.perform_later('0987zyx', 1, true)
+
+      begin
+        perform_enqueued_jobs
+      rescue # rubocop:disable Style/RescueStandardError terrible pattern in almost all cases, but acceptable here
```
Comment (jmartin-sul) [inline spec/jobs/application_job_spec.rb:61]: now that i think about it, i guess i could raise and trap for a custom error, to reduce the chance of a test passing but hiding another issue if code is changed later.  happy to do that if others think it's worth it.

File: spec/jobs/application_job_spec.rb [hunk 7]
```diff
@@ -2,34 +2,78 @@
...
+        # the error is bubbling up to here despite coming from an async job.  IRL, this would not happen.
+        # no idea why ActiveJob is behaving differently in the tests.
```
Comment (jmartin-sul) [inline spec/jobs/application_job_spec.rb:63]: also, now that i think about this, maybe this comment is off-base.  app code that uses ActiveJob really only ever queues jobs, and doesn't pick them up for execution, and whatever adapter actually runs the job probably does have to deal with this sort of error.  will fix...

File: spec/jobs/application_job_spec.rb [hunk 8]
```diff
@@ -2,34 +2,78 @@
...
+      end
+
+      expect { RegularParameterJob.perform_later('0987zyx', 1, true) }
+        .to change(enqueued_jobs, :size).from(0).to(1)
+    end
+
+    it 'enqueues the job if it detects an existing lock that has expired' do
+      RegularParameterJob.perform_later('4321cba', 1, false)
+
+      sleep(RegularParameterJob.lock_timeout + 3) # lock timeout is very short, this should go well past it
```
Comment (jmartin-sul) [inline spec/jobs/application_job_spec.rb:73]: i always feel bad `sleep`ing in tests, but i looked and there's actually only one other `sleep` in the tests, for 0.1 seconds.  totally open to non-`sleep` suggestions for testing timeout.

File: spec/jobs/application_job_spec.rb [hunk 9]
```diff
@@ -38,24 +82,23 @@
     let(:cm2) { create :complete_moab }
 
     before do
-      allow(CatalogToMoabJob).to receive(:perform_later).and_call_original # undo rails_helper block
```
Comment (jmartin-sul) [inline spec/jobs/application_job_spec.rb:41]: turns out this wasn't needed because rails_helper doesn't intercept `CatalogToMoabJob.perform_later`.  maybe cruft.

File: spec/requests/objects_controller_validate_moab_spec.rb [hunk 10]
```diff
@@ -9,7 +9,7 @@
   describe 'GET #validate_moab' do
     context 'when valid druid passed in' do
       before do
-        allow(ValidateMoabJob).to receive(:perform_later).and_return(true)
+        allow(ValidateMoabJob).to receive(:perform_later).and_return(ValidateMoabJob.new)
```
Comment (jmartin-sul) [inline spec/requests/objects_controller_validate_moab_spec.rb:12]: tweaked to give slightly more realistic mocking since i was revising related code and adding tests anyway

File: app/controllers/objects_controller.rb [hunk 11]
```diff
@@ -15,8 +15,18 @@ def show
...
+    # The most likely cause is a temporary queue lock for the job and its specific payload, so
+    # it is up to the caller to determine whether retrying later is appropriate.
+    if ValidateMoabJob.perform_later(druid)
+      render(plain: 'ok', status: :ok)
+    else
+      err_msg = "Failed to enqueue ValidateMoabJob for #{druid}. "\
+                'The most likely cause is that the job was already enqueued and is waiting to be picked up. '\
+                'Retry later if appropriate.'
+      render(plain: err_msg, status: :locked)
+    end
```
Comment (ndushay) [inline app/controllers/objects_controller.rb:29]: This looks awesome ... wonder if this affects ... other robots?   Other queuing systems besides resque?  Etc.  If it's just about resque ... maybe it should say? 

And how sure are you about this ?

**Review by justinlittman — APPROVED** [review]

File: app/jobs/application_job.rb [hunk 12]
```diff
@@ -21,16 +20,69 @@ class ApplicationJob < ActiveJob::Base
...
+    key = queue_lock_key(*args)
+    now = Time.now.to_i
+    new_expiry_time = now + lock_timeout + 1
+
+    # return true if we successfully acquired the lock
+    # "Set key to hold string value if key does not exist" (otherwise no-op) -- https://redis.io/commands/setnx
+    if Resque.redis.setnx(key, new_expiry_time)
+      Rails.logger.info("acquired lock on #{key} (none existed)")
```
Comment (ndushay) [inline app/jobs/application_job.rb:54]: debug level rather than info?

File: app/jobs/application_job.rb [hunk 13]
```diff
@@ -21,16 +20,69 @@ class ApplicationJob < ActiveJob::Base
...
+      return true
+    end
+
+    # see if the existing lock is still valid and return false if it is
+    # (we cannot acquire the lock during the timeout period)
+    key_expires_at = Resque.redis.get(key).to_i
+    if now <= key_expires_at
+      Rails.logger.info("failed to acquire lock on #{key}, because it has not expired (#{now} <= #{key_expires_at})")
```
Comment (ndushay) [inline app/jobs/application_job.rb:62]: ditto - debug level rather than info?

File: app/jobs/application_job.rb [hunk 14]
```diff
@@ -21,16 +20,69 @@ class ApplicationJob < ActiveJob::Base
...
+      return false
+    end
+
+    # otherwise set the new_expiry_time and ensure that no other worker has
+    # acquired the lock, possibly pushing out the expiry time further
+    # "Atomically sets key to value and returns the old value stored at key." -- https://redis.io/commands/getset
+    key_expires_at = Resque.redis.getset(key, new_expiry_time).to_i
+    if now > key_expires_at
+      Rails.logger.info("acquired lock on #{key} (old lock expired, #{now} > #{key_expires_at})")
```
Comment (ndushay) [inline app/jobs/application_job.rb:71]: ditto

File: app/jobs/application_job.rb [hunk 15]
```diff
@@ -21,16 +20,69 @@ class ApplicationJob < ActiveJob::Base
...
+      true
+    else
+      Rails.logger.info("failed to acquire lock on #{key} but updated expiry time to #{new_expiry_time} (#{now} <= #{key_expires_at})")
```
Comment (ndushay) [inline app/jobs/application_job.rb:74]: warn? no idea.

File: app/jobs/application_job.rb (hunk 1 above)
Comment (ndushay) [reply app/jobs/application_job.rb:75]: i'm fine with this - this isn't the only else clause untested in the portfolio.

File: app/jobs/application_job.rb [hunk 16]
```diff
@@ -21,16 +20,69 @@ class ApplicationJob < ActiveJob::Base
...
+      false
+    end
+  end
+
+  def self.clear_lock(*args)
+    key = queue_lock_key(*args)
+    Rails.logger.info("clearing lock for #{key}...")
+    Resque.redis.del(key).tap do |del_result|
+      Rails.logger.info("...cleared lock for #{key} (del_result=#{del_result})")
```
Comment (ndushay) [inline app/jobs/application_job.rb:83]: both of these as debug?

File: app/jobs/application_job.rb (hunk 2 above)
Comment (ndushay) [reply app/jobs/application_job.rb:139]: This is definitely a good faith attempt;  no idea what is correct, but I think this is sufficient.

File: app/jobs/application_job.rb [hunk 17]
```diff
@@ -53,3 +105,35 @@ def zip_info_check!(metadata)
     end
   end
 end
+
+# Q: Why copy the logic out of resque-lock instead of using the gem?
+# A: It's a small amount of (MIT licensed) code, the gem is and unmaintained (last updated in 2012),
+# and the lock cleanup hook wasn't getting invoked automatically in our jobs.  Inlining the code
+# reduces indirection and dependency (on both resque-lock and on Resque itself, since we use ActiveJob
+# hooks here instead of Resque hooks).
```
Comment (ndushay) [inline app/jobs/application_job.rb:113]: I think in the future, no one will remember there was a resque-lock gem.  I think adding "gem" after resque-lock below might be sufficient, and leave lines 109-113 out.   If you're attached to the above, that's fine too.

File: app/jobs/zip_part_job_base.rb [hunk 18]
```diff
@@ -11,8 +11,8 @@ class ZipPartJobBase < ApplicationJob
   end
 
   # Does queue locking on ONLY druid, version and part (as first 3 parameters)
-  def self.lock(*args)
-    "lock:#{name}-#{args.slice(0..2)}"
+  def self.queue_lock_key(*args)
```
Comment (ndushay) [inline app/jobs/zip_part_job_base.rb:14]: is this doing the locking, or getting a key?   the name is a bit confusing.  I'd sooner see "queue_lock" with a comment about it returning the key, or about it returning the key as a side effect ... or something like that.

**Review by ndushay — APPROVED** [review]
I have nothing blocking this PR and would suggest merging and deploying immediately so it gets most of today to shake out any unexpected (tautology) problems.

My thoughts:
- level of logging messages might want to be debug and a warn for the else case
- wonder if the lock thing would make sense as a separate class ... it's sort of indirect as a part of application_job.rb.   If this isn't a poor idea, I suggest merging this and doing a separate PR, or making it an issue ... it's not urgent.
- `queue_lock_key` to me implies you're getting a key, not doing the locking.  if it's doing both, I care more about the locking happening, and the key being returned as maybe a side effect?

File: app/controllers/objects_controller.rb (hunk 11 above)
Comment (jmartin-sul) [reply app/controllers/objects_controller.rb:29]: > wonder if this affects ... other robots?

I don't think so... since this method (AFAIK) is only invoked by the new `validate-moab` step's robot.

>  Other queuing systems besides resque?

This uses ActiveJob behavior, and so shouldn't be specific to resque.  I mean, practically, I think we'd have trouble switching from e.g. resque to sidekiq because moab-versioning caches things in class vars (iirc), which isn't thread safe (and so isn't sidekiq safe).  But this, at least, shouldn't block switching 🙂

> And how sure are you about this ?

Very sure that this behavior will work in rails 6.1.x (based on lots of testing in rails console in the course of other testing for this PR).  And after some research yesterday, also fairly certain this will work in rails 6.2+...

The `new_framework_defaults_6_0.rb` file has a config entry `Rails.application.config.active_job.return_false_on_aborted_enqueue = true`.  This actually generates a deprecation warning, `DEPRECATION WARNING: return_false_on_aborted_enqueue= is deprecated and will be removed from Rails 6.2`.  this was worrisome, but after some research, what i found indicated that the old default was `false`, and that the old behavior was to return an instance of the job regardless of whether it was successfully queued.  since we had not previously inspected or acted on the output of our `ActiveJob::Base.perform_later` calls, we were able to switch what will be the default behavior in rails 6.2 onward, when we upgraded to rails 6 in dec 2019.

see:
* https://guides.rubyonrails.org/v6.0.3/configuring.html#configuring-active-job (end of section)
* https://github.com/rails/rails/blob/v6.0.4/activejob/CHANGELOG.md#rails-600beta1-january-18-2019
* https://guides.rubyonrails.org/v6.2.0/configuring.html#configuring-active-job (no longer mentions the config field, also note this redirects to the `edgeguides.` URL since 6.2.x is the current latest)

i believe the deprecation warning is because you'll no longer be able to configure the old behavior in 6.2+.

might be good to get confirmation from e.g. @jcoyne on this, since he did the upgrade to rails 6 on this app (iirc), and since he's generally more up on this sort of rails behavioral detail than i am.

Comment (jmartin-sul) [reply app/controllers/objects_controller.rb:29]: example from random testing, where i attempt to re-queue a checksum validation job for the same moab before the first job for that moab finished working:

```
[18] pry(main)> ChecksumValidationJob.perform_later(cm)
acquired lock on lock:ChecksumValidationJob-gid://preservation-catalog/CompleteMoab/25315 (none existed)
Enqueued ChecksumValidationJob (Job ID: 37bb8216-40a2-4d6d-97ce-45dac35dabb0) to Resque(checksum_validation) with arguments: #<GlobalID:0x0000000005a45ce0 @uri=#<URI::GID gid://preservation-catalog/CompleteMoab/25315>>
=> #<ChecksumValidationJob:0x0000000005ac8550
 @arguments=
  [#<CompleteMoab:0x00000000062ba178
    id: 25315,
    version: 2,
    preserved_object_id: 25301,
    moab_storage_root_id: 18,
    created_at: Wed, 11 Mar 2020 16:04:37.670398000 UTC +00:00,
    updated_at: Thu, 30 Apr 2020 16:56:11.688153000 UTC +00:00,
    last_moab_validation: Wed, 11 Mar 2020 16:04:37.664436000 UTC +00:00,
    last_checksum_validation: Thu, 30 Apr 2020 16:56:11.686353000 UTC +00:00,
    size: 609026338,
    status: "ok",
    last_version_audit: Thu, 30 Apr 2020 16:56:11.686309000 UTC +00:00,
    status_details: nil,
    from_moab_storage_root_id: nil>],
 @exception_executions={},
 @executions=0,
 @job_id="37bb8216-40a2-4d6d-97ce-45dac35dabb0",
 @priority=nil,
 @queue_name="checksum_validation",
 @timezone="UTC">
[19] pry(main)> ChecksumValidationJob.perform_later(cm)
failed to acquire lock on lock:ChecksumValidationJob-gid://preservation-catalog/CompleteMoab/25315, because it has not expired (1625188536 <= 1625192135)
Failed enqueuing ChecksumValidationJob to Resque(checksum_validation), a before_enqueue callback halted the enqueuing execution.
=> false
```

File: app/jobs/zip_part_job_base.rb (hunk 18 above)
Comment (jmartin-sul) [reply app/jobs/zip_part_job_base.rb:14]: this only computes the key for the lock, and is used by other methods (via the superclass in this case) both to try to set the lock, and to clear it.  i'd wanted to avoid just `lock` or `queue_lock` as a name, because both felt ambiguous as to whether they were setting the lock, or returning a lock object (though the method does neither of those things).

i think this ends up being clearer in the base class, with the surrounding context of the other callers and stuff... maybe a better comment here would suffice?  also happy to consider other names if the name itself is what seems really off-base.

**Comment by jmartin-sul** [comment]
thanks for the quick reviews @justinlittman and @ndushay!

since this was approved, i'm going to merge, and address naomi's suggestions in a follow-on PR.

File: app/controllers/objects_controller.rb (hunk 11 above)
Comment (ndushay) [reply app/controllers/objects_controller.rb:29]: I was wondering about common-accessioning, which definitely uses a lot of perform-later and also uses resque.   Less so about within prescat.

File: app/jobs/zip_part_job_base.rb (hunk 18 above)
Comment (ndushay) [reply app/jobs/zip_part_job_base.rb:14]: maybe, if it's not actually doing the locking, just change the comment here (and in other similar spots) to something like "key will ensure we lock on a combination of druid, version, and part (first 3 parameters)" or something like that.   Makes it clear it's just a key, and this method isn't performing the lock.  :-)

File: spec/jobs/application_job_spec.rb (hunk 8 above)
Comment (ndushay) [reply spec/jobs/application_job_spec.rb:74]: Seems the way around this would be to look for an existing lock, but if that code isn't already available to us (maybe it's private methods in resque or something), then meh.   I do hate sleeps, and I hate tests taking longer than they should ... but this can be a separate ticket.

**Comment by jcoyne** [comment]
I don't understand why we need or want to in-line a library.
