### PR TITLE
Use .save! instead of custom method to save db objects

### LINKED ISSUE #478: (M2C) (C2M) PreservedObjectHandler.update_db_object:  do we still want it? or just .save!
This is critical path if it impacts the writing of C2M;  otherwise it is refactoring.

I think with our new understanding of our timestamps, we now are served by doing a simple `PreservedCopy.save!` or `PreservedObject.save!` which will do the right thing, yes?  We can leave `updated_at` timestamp to its natural behavior?

Thus, the method below becomes superfluous (do we really need to have those particular handler results???).

Note that there are rubocop exceptions tied to this code (for the `touch` method, I believe, if nothing else) that should also go away ...

current code (https://github.com/sul-dlss/preservation_catalog/blob/master/app/services/preserved_object_handler.rb#L372L383)

```ruby
# TODO: this may need reworking if we need to distinguish db timestamp updates when
  #   version matched vs. incoming version less than db object
  def update_db_object(db_object)
    if db_object.changed?
      db_object.save!
      handler_results.add_result(PreservedObjectHandlerResults::UPDATED_DB_OBJECT, db_object.class.name)
    else
      # FIXME: we may not want to do this, but instead to update specific timestamp for check
      db_object.touch
      handler_results.add_result(PreservedObjectHandlerResults::UPDATED_DB_OBJECT_TIMESTAMP_ONLY, db_object.class.name)
    end
  end
```

### PR DESCRIPTION
**Pull request by tallenaz**
Closes #478 

Could probably use more than 1 set of eyes, since this touches a lot of code.

### CODE REVIEW

File: spec/services/preserved_object_handler_check_exist_spec.rb [hunk 1]
```diff
@@ -470,10 +450,10 @@
         allow(pc).to receive(:version).and_return(1)
         allow(pc).to receive(:update_audit_timestamps)
         allow(pc).to receive(:changed?).and_return(false)
-        allow(pc).to receive(:touch)
+        allow(pc).to receive(:save!)
```
Comment (jmartin-sul) [inline spec/services/preserved_object_handler_check_exist_spec.rb]: looks like the test needs a rename now too

File: spec/services/preserved_object_handler_confirm_version_spec.rb [hunk 2]
```diff
@@ -307,11 +295,11 @@
         allow(pc).to receive(:version).and_return(1)
         allow(pc).to receive(:update_audit_timestamps)
         allow(pc).to receive(:changed?).and_return(false)
-        allow(pc).to receive(:touch)
+        allow(pc).to receive(:save!)
```
Comment (jmartin-sul) [inline spec/services/preserved_object_handler_confirm_version_spec.rb]: ditto this test name

File: spec/services/preserved_object_handler_check_exist_spec.rb [hunk 3]
```diff
@@ -457,23 +437,21 @@
         end
       end
 
-      it 'calls PreservedCopy.touch (but not PreservedObject.touch) if the existing record is NOT altered' do
+      it 'calls PreservedCopy.save! if the existing record is NOT altered' do
```
Comment (ndushay) [inline spec/services/preserved_object_handler_check_exist_spec.rb]: how about "calls PreservedCopy.save! (but note PreservedObject.save!) if the existing version is NOT altered" ?

The original test shows that PreservedCopy timestamps are updated, but PreservedObject was unchanged.

File: spec/services/preserved_object_handler_check_exist_spec.rb [hunk 4]
```diff
@@ -457,23 +437,21 @@
...
         po_handler = described_class.new(druid, 1, 1, ep)
         po = instance_double(PreservedObject)
         pc = instance_double(PreservedCopy)
         allow(PreservedObject).to receive(:find_by!).with(druid: druid).and_return(po)
         allow(po).to receive(:current_version).and_return(1)
-        allow(po).to receive(:touch)
```
Comment (ndushay) [inline spec/services/preserved_object_handler_check_exist_spec.rb]: which would change this line to be included, but :save! instead of :touch

File: spec/services/preserved_object_handler_check_exist_spec.rb [hunk 5]
```diff
@@ -457,23 +437,21 @@
...
         allow(PreservedCopy).to receive(:find_by!).with(preserved_object: po, endpoint: ep).and_return(pc)
         allow(pc).to receive(:matches_po_current_version?).and_return(true)
         allow(pc).to receive(:status).and_return(PreservedCopy::OK_STATUS)
         allow(pc).to receive(:version).and_return(1)
         allow(pc).to receive(:update_audit_timestamps)
         allow(pc).to receive(:changed?).and_return(false)
-        allow(pc).to receive(:touch)
+        allow(pc).to receive(:save!)
         po_handler.check_existence
-        expect(po).not_to have_received(:touch)
```
Comment (ndushay) [inline spec/services/preserved_object_handler_check_exist_spec.rb]: and would change this line to be included, but :save! instead of :touch

File: spec/services/preserved_object_handler_confirm_version_spec.rb [hunk 6]
```diff
@@ -295,23 +283,21 @@
         expect(po).not_to have_received(:save!)
         expect(pc).to have_received(:save!)
       end
-      it 'calls PreservedCopy.touch (but not PreservedObject.touch) if the existing record is NOT altered' do
+      it 'calls PreservedCopy.save! if the existing record is NOT altered' do
```
Comment (ndushay) [inline spec/services/preserved_object_handler_confirm_version_spec.rb]: save as in check_existence spec:  this test shows that PreservedCopy timestamps were updated for the check, but PreservedObject remained unchanged.

File: spec/services/preserved_object_handler_update_version_spec.rb [hunk 7]
```diff
@@ -249,26 +230,6 @@
         expect(pc).to have_received(:save!)
       end
 
-      it 'does not call PreservedObject.touch when PreservedCopy only has timestamp updates' do
```
Comment (ndushay) [inline spec/services/preserved_object_handler_update_version_spec.rb]: again save as in check_existence spec:  this test shows that PreservedCopy timestamps were updated for the check, but PreservedObject remained unchanged.  So test should stay, but be modified

File: spec/services/preserved_object_handler_update_version_spec.rb [hunk 8]
```diff
@@ -458,27 +419,6 @@
           expect(Rails.logger).to have_received(:debug).with(msg)
         end
 
-        it 'does not call PreservedObject.touch when PreservedCopy only has timestamp updates' do
```
Comment (ndushay) [inline spec/services/preserved_object_handler_update_version_spec.rb]: ditto for this test

File: app/services/preserved_object_handler_results.rb [hunk 9]
```diff
@@ -10,25 +10,21 @@ class PreservedObjectHandlerResults
...
+  PC_PO_VERSION_MISMATCH = 12
+  ONLINE_MOAB_DOES_NOT_EXIST = 13
 
   RESPONSE_CODE_TO_MESSAGES = {
     INVALID_ARGUMENTS => "encountered validation error(s): %{addl}",
     VERSION_MATCHES => "incoming version (%{incoming_version}) matches %{addl} db version",
     ARG_VERSION_GREATER_THAN_DB_OBJECT => "incoming version (%{incoming_version}) greater than %{addl} db version",
     ARG_VERSION_LESS_THAN_DB_OBJECT => "incoming version (%{incoming_version}) less than %{addl} db version; ERROR!",
-    UPDATED_DB_OBJECT => "%{addl} db object updated",
-    UPDATED_DB_OBJECT_TIMESTAMP_ONLY => "%{addl} updated db timestamp only",
```
Comment (ndushay) [inline app/services/preserved_object_handler_results.rb]: heh - funny how we're all comfortable calling this "noise" now.  Yay us!
