### PR TITLE
fix openapi for checksum

### LINKED ISSUE #1434: Checksum report fails on accessioned objects, error from preservation catalog API
**Describe the bug**
When running a checksum report on a set of accessioned objects, the report will error out.

**User Impact**
Users are unable to do checksum comparisons on large sets of objects in the SDR against those on staging servers.

**Object(s) In This Error State**

n/a

Steps to Reproduce, if Known:

Take an example set of objects, i.e. https://argo.stanford.edu/catalog?utf8=%E2%9C%93&q=%22JIRA+%3A+DIGREQ-1585%22

Bulk action --> new bulk action --> checksum report

**Expected behavior**

On the results page, the total objects and success numbers should be identical. Right now, all objects are failing.

**Screenshots**
2020-03-10 16:40:36 UTC Starting ChecksumReportJob for BulkAction 8594
2020-03-10 16:40:36 UTC ChecksumReportJob got error from Preservation Catalog API (Preservation::Client::UnexpectedResponseError): Preservation::Client.http_response got 400 from Preservation at v1/objects/checksums: {"errors":[{"status":"bad_request","detail":"\"Content-Type\" request header must be set to \"application/x-www-form-urlencoded\"."}]}
2020-03-10 16:40:36 UTC Finished ChecksumReportJob for BulkAction 8594

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

to fix #1434 (checksum report failing) likely due to new enforcement in openapi 

## Was the usage documentation (e.g. wiki, README, queue or DB specific README) updated?

no

## Does this change affect how this application integrates with other services?
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.

no

### CODE REVIEW

File: spec/requests/objects_controller_checksums_spec.rb [hunk 1]
```diff
@@ -199,16 +200,16 @@
     context 'when no druids param' do
       context 'when param is empty' do
         it 'body has additional information from the exception if available' do
-          post checksums_objects_url, params: { druids: [], format: :json }, headers: valid_auth_header
+          post checksums_objects_url, params: { druids: [], format: :json }.to_json, headers: post_headers
           expect(response).to have_http_status(:bad_request)
           error_response = JSON.parse(response.body)['errors'].first
-          expect(error_response['detail']).to include('does not match value: , example: druid:bc123df4567')
+          expect(error_response['detail']).to include('druids [] contains fewer than min items')
```
Comment (mjgiarlo) [inline spec/requests/objects_controller_checksums_spec.rb]: Hmmm, curious about this change.

Comment (peetucket) [reply spec/requests/objects_controller_checksums_spec.rb]: came about because openapi is enforcing a minimum number of druids, which is triggering a different response

Comment (mjgiarlo) [reply spec/requests/objects_controller_checksums_spec.rb]: I guess I don't get how this wasn't failing before. I wouldn't expect changing the content-type of the request body to make this start failing.

Comment (peetucket) [reply spec/requests/objects_controller_checksums_spec.rb]: i think there wasn't any enforcement of openapi before at all, so there two failures occurring (content type and druid missing) now

File: openapi.yml [hunk 2]
```diff
@@ -216,7 +216,7 @@ paths:
       requestBody:
         required: true
         content:
-          application/x-www-form-urlencoded:
+          application/json:
```
Comment (ndushay) [inline openapi.yml]: @mjgiarlo !!!!

Comment (mjgiarlo) [reply openapi.yml]: @ndushay yessss? This was another instance where the prescat test suite tested different behavior from the implementation in pres-client, if this is like the other related change. I trusted the test suite. 😁
