### PR TITLE
Fix archive pres copy creation (depends on #956, #954)

### LINKED ISSUE #899: (R) can't get what needs to be replicated
```
=> #<PreservedCopy:0x00000000078913e8
 id: 33,
 version: 3,
 preserved_object_id: 33,
 endpoint_id: 7,
 created_at: Thu, 07 Jun 2018 23:37:06 UTC +00:00,
 updated_at: Thu, 07 Jun 2018 23:37:06 UTC +00:00,
 last_moab_validation: Thu, 07 Jun 2018 23:37:06 UTC +00:00,
 last_checksum_validation: nil,
 size: 150321967,
 status: "validity_unknown",
 last_version_audit: Thu, 07 Jun 2018 23:37:06 UTC +00:00>
[44] pry(main)> pc.status = 'ok'
=> "ok"
[45] pry(main)> pc.save!
=> true
[46] pry(main)> pc.preserved_object.create_archive_preserved_copies(3)
=> []
[47] pry(main)> pc.preserved_object.create_archive_preserved_copies(2)
=> []
```

Maybe last_checksum_validation needs to be not nil? After running CV status was changed to `ok` as well.

```
[3] pry(main)> pc
=> #<PreservedCopy:0x0000000004447600
 id: 33,
 version: 3,
 preserved_object_id: 33,
 endpoint_id: 7,
 created_at: Thu, 07 Jun 2018 23:37:06 UTC +00:00,
 updated_at: Mon, 18 Jun 2018 21:19:32 UTC +00:00,
 last_moab_validation: Mon, 18 Jun 2018 21:19:32 UTC +00:00,
 last_checksum_validation: Mon, 18 Jun 2018 21:19:32 UTC +00:00,
 size: 150321967,
 status: "ok",
 last_version_audit: Mon, 18 Jun 2018 21:19:32 UTC +00:00>
[4] pry(main)> pc.preserved_object
=> #<PreservedObject:0x0000000006169d00
 id: 33,
 druid: "bc656gn1417",
 current_version: 3,
 created_at: Thu, 07 Jun 2018 23:37:06 UTC +00:00,
 updated_at: Thu, 07 Jun 2018 23:37:06 UTC +00:00,
 preservation_policy_id: 1>
[5] pry(main)> pc.preserved_object.create_archive_preserved_copies(2)
=> []
```

### PR DESCRIPTION
**Pull request by jmartin-sul**
ported and fixed the query, and added a test which would've demonstrated issue #899.

still need to:
- [x] finish porting `create_archive_preserved_copies!` to `PreservedCopy`
- [x] port/write tests for `PreservedCopy.create_archive_preserved_copies!`
- [x] write tests for `ArchiveEndpoint.which_have_archive_copy`
- [x] ~~remove `Endpoint.which_need_archive_copy` (will likely happen after rebasing on the below mentioned PRs anyway)~~ yup, 954 took care of it
- [x] rebase on master after #956 is merged
- [x] rebase on master after #954 is merged

i think the tentative plan is to get #956 merged, then #954, then this.

fixes #899

### CODE REVIEW

**Comment by SaravShah** [comment]
cool `which_have` and `which_need` `archive_preserved_copies` verified working

**Comment by jmartin-sul** [comment]
ready for review (@ndushay, @SaravShah, @tallenaz)

File: spec/models/preserved_copy_spec.rb [hunk 1]
```diff
@@ -309,4 +314,53 @@
       end
     end
   end
+
+  describe '#create_archive_preserved_copies!' do
```
Comment (jmartin-sul) [inline spec/models/preserved_copy_spec.rb]: one thing i'd considered was writing tests for `#create_archive_preserved_copies!` that used two different druids, similarly to what i did for the `which_have_archive_copy` and `which_need_archive_copy` scopes on `ArchiveEndpoint`.  i'd still be open to do that, but felt like this was complete enough to be a PR as-is, especially since the scope that `#create_archive_preserved_copies!` relies on to figure out what to create is tested in that way.  figured it might be better to get this merged and ticket follow-on work.

File: app/models/archive_endpoint.rb [hunk 2]
```diff
@@ -16,6 +16,23 @@ class ArchiveEndpoint < ApplicationRecord
...
+
+  scope :which_have_archive_copy, lambda { |druid, version|
+    joins(archive_preserved_copies: [:preserved_object])
+      .where(
+        preserved_objects: { druid: druid },
+        archive_preserved_copies: { version: version }
+      )
+  }
+
+  scope :which_need_archive_copy, lambda { |druid, version|
```
Comment (jmartin-sul) [inline app/models/archive_endpoint.rb]: @SaravShah had suggested trying to work some bounds checking into the query, so that it doesn't return results for versions greater than the current version on the preserved object.  i'd like to try to do that, but it's not immediately clear to me what the query would be, so i have a slight preference for getting this merged and trying to do that as follow-on work.

if we did do that bounds checking in this query, it might or might not obviate the need for it in `PreservedCopy#create_archive_preserved_copies!`... i still sorta like the idea of failing noisily if an out of bounds version is given to that method, but i don't feel super-strongly about that.

File: app/models/archive_endpoint.rb [hunk 3]
```diff
@@ -16,6 +16,23 @@ class ArchiveEndpoint < ApplicationRecord
   # TODO: after switching to string, validate that input resolves to class which #is_a class of the right type?
   validates :delivery_class, presence: true
 
+  # for the given druid, which archive endpoints should have archive copies?
+  scope :archive_targets, lambda { |druid|
+    joins(preservation_policies: [:preserved_objects]).where(preserved_objects: { druid: druid })
+  }
+
+  scope :which_have_archive_copy, lambda { |druid, version|
```
Comment (ndushay) [inline app/models/archive_endpoint.rb]: maybe add comment:
"for a druid, version, which zip_endpoints have  zipped_moab_versions  for the complete_moab?"

File: app/models/archive_endpoint.rb (hunk 2 above)
Comment (ndushay) [inline app/models/archive_endpoint.rb]: maybe add comment:

"for a druid, version, which zip_endpoints need a zipped_moab_version, per preservation_policy"

File: spec/models/archive_endpoint_spec.rb [hunk 4]
```diff
@@ -73,4 +73,82 @@
       expect(described_class.pluck(:endpoint_name).sort).to eq expected_ep_names
     end
   end
+
+  describe '.archive_targets' do
+    let!(:alternate_pres_policy) do
```
Comment (SaravShah) [inline spec/models/archive_endpoint_spec.rb]: do we want a factory for preservation policy?

File: spec/models/archive_endpoint_spec.rb [hunk 5]
```diff
@@ -73,4 +73,82 @@
...
+    let!(:po) { create(:preserved_object, current_version: version, druid: druid) }
+    let(:pc) { create(:preserved_copy, preserved_object: po) }
+    let(:other_druid) { 'zy098xw7654' }
+    let!(:pc_other_druid) do
+      other_po = create(:preserved_object, current_version: version, druid: other_druid)
+      create(:preserved_copy, version: version, preserved_object: other_po)
+    end
+    let(:ma1_ep) { ArchiveEndpoint.find_by!(endpoint_name: 'mock_archive1') }
+
+    # TODO: try expecting to eq a set
```
Comment (ndushay) [inline spec/models/archive_endpoint_spec.rb]: stray comment?

Comment (SaravShah) [inline spec/models/archive_endpoint_spec.rb]: do we need to remove this comment?

**Comment by jmartin-sul** [comment]
will leave comments per @ndushay's suggestions (and will get rid of the stray that she caught)

File: spec/models/archive_endpoint_spec.rb (hunk 4 above)
Comment (jmartin-sul) [reply spec/models/archive_endpoint_spec.rb]: would be inclined to do that as another PR, but seems like a good idea

File: app/models/archive_endpoint.rb (hunk 2 above)
Comment (SaravShah) [reply app/models/archive_endpoint.rb]: follow-on ticket sounds good to me.

File: spec/models/preserved_copy_spec.rb (hunk 1 above)
Comment (SaravShah) [inline spec/models/preserved_copy_spec.rb]: Add 2 tests:
1. ` expect { pc.create_archive_preserved_copies!(pc_version) }.to eq [ ArchivePreservedcopy object]`

2.  `create(:archive_preserved_copy)`
`expect { pc.create_archive_preserved_copies!(pc_version) }.to eq [] `

Comment (SaravShah) [reply spec/models/preserved_copy_spec.rb]: So we expect that create_archive_preserved_copies returns the archive preserved copies we actually want, AND if we already have the archive preserved copies created, and we call the create_archive_preserved_copies, that method does not return any archive preserved copy objects.

File: app/models/archive_endpoint.rb (hunk 2 above)
Comment (jmartin-sul) [reply app/models/archive_endpoint.rb]: #983

File: spec/models/archive_endpoint_spec.rb (hunk 4 above)
Comment (jmartin-sul) [reply spec/models/archive_endpoint_spec.rb]: #984

File: spec/models/preserved_copy_spec.rb (hunk 1 above)
Comment (jmartin-sul) [reply spec/models/preserved_copy_spec.rb]: right, the method should only create the missing archive copies, and the method should return whatever copies it created.

so, e.g., if no copies were needed, an empty array should be returned.  if a new archive endpoint got added and connected to the relevant preservation policy, the method should create one new archive copy, and should return an instance of that archive copy.

Comment (jmartin-sul) [reply spec/models/preserved_copy_spec.rb]: #985

**Comment by jmartin-sul** [comment]
ok @ndushay and @SaravShah, i believe i've addressed all feedback so far, either by making the requested changes, or by filing and linking issues for follow-on work.  ready for re-review...

File: spec/models/preserved_copy_spec.rb (hunk 1 above)
Comment (tallenaz) [reply spec/models/preserved_copy_spec.rb]: I agree it would be a good idea to have tests for `create_archive_preserved_copies!` using 2 different druids, and also agree that's fine for follow-on work. Otherwise LGTM.

Comment (jmartin-sul) [reply spec/models/preserved_copy_spec.rb]: #986
