### PR TITLE
Fix #844: Zip util outputs "errors" on STDOUT

### LINKED ISSUE #844: Capture STDOUT from zip (it has error messages, STDERR empty)
Example:
```bash
> zip -vr0X -s 10g /tmp/jj/925/bx/9565/jj925bx9565.v0002.zip spec/fixtures/storage_root01/moab_storage_trunk/jj/925/bx/9565/jj925bx9565/v0002
zip I/O error: No such file or directory
zip error: Could not create output file (/tmp/jj/925/bx/9565/jj925bx9565.v0002.zip)
> zip -vr0X -s 10g /tmp/jj/925/bx/9565/jj925bx9565.v0002.zip spec/fixtures/storage_root01/moab_storage_trunk/jj/925/bx/9565/jj925bx9565/v0002 >/dev/null
```
That "error" message is only sent to STDOUT.

Convert `Open3.capture3` call to `Open3. capture2e ` (combines STDERR and STDOUT).

### PR DESCRIPTION
**Pull request by atz**
Makes error reporting work.  As a bonus, one less unused variable.

### CODE REVIEW

File: spec/jobs/zipmaker_job_spec.rb [hunk 1]
```diff
@@ -61,15 +61,15 @@
...
 
         it 'raises error' do
-          expect { job.create_zip! }.to raise_error(RuntimeError, /zipmaker failure/)
+          expect { job.create_zip! }.to raise_error(RuntimeError, %r{zipmaker failure.*/wrong/path})
         end
       end
 
       context 'when options are unsupported' do
-        let(:zip_command) { "zip -a #{zip_path} #{moab_version_path}" }
+        let(:zip_command) { "zip --fantasy #{zip_path} #{moab_version_path}" }
```
Comment (tallenaz) [inline spec/jobs/zipmaker_job_spec.rb]: Now I've got Aldo Nova stuck in my head :)
