### PR TITLE
PreservedObjectHandler.update_version_after_validation implemented

### LINKED ISSUE #283: (M2C) (UC) (PC)  update_version_after_validation method in pohandler
pohandler needs a public method to call MV/D2D before calling (plain) update_version.

check_existence will use update_version_with_validation.  

Ingest robot for new version will have a feature flag to use update_version_with_validation or just plain update_version

### LINKED ISSUE #287: (M2C) (UC) pohandler.update_version (w, w/o validation)  timestamps to update
(See also #278 and #286)

update_version (with or without validation) updates timestamps:

#### happy path:  version in PC updated:
PC:
- version
- updated_at (via ActiveRecord)
- if update_version_with_validation:
    - last_audited field
    - last_checked_on_storage field

PO:
- current_version
- updated_at  (via ActiveRecord)

#### if incoming version <= catalog version
ERROR (bad args) to caller
- this is not a status change but a "hey caller you have bad data" error:
    - if equal version to incoming, then caller has a problem version
    - if catalog higher than incoming, then caller also has a problem version

PC
- if update_version_with_validation:
   - last_audited field
   - last_checked_on_storage field
     
PO
- do nothing

#### if object does not exist:  it's an error.

### PR DESCRIPTION
**Pull request by ndushay**
Implements `#update_version_after_validation` method in PreservedObjectHandler.

Also added FIXME notes in #confirm_version implementation methods.

closes #283 
closes #287

### CODE REVIEW

File: app/services/preserved_object_handler.rb [hunk 1]
```diff
@@ -211,14 +247,16 @@ def with_active_record_transaction_and_rescue
...
   # expects @incoming_version to be numeric
-  def update_preserved_copy(pres_copy, new_version, new_size)
+  def update_preserved_copy_version_etc(pres_copy, new_version, new_size, validated=false)
     pres_copy.version = new_version
     pres_copy.size = new_size if new_size
+    update_pc_validation_timestamps(pres_copy) if validated
   end
 
-  # expects @incoming_version to be numeric
-  def update_preserved_object(pres_obj, new_version)
```
Comment (ndushay) [inline app/services/preserved_object_handler.rb]: note that I decided the `update_preserved_object` one liner method was stupid and better served with inline code.

File: spec/services/preserved_object_handler_update_version_spec.rb [hunk 2]
```diff
@@ -340,4 +334,370 @@
...
+            expect(pc.reload.size).to eq 1
+          end
+          it 'updates PreservedCopy last_audited field' do
+            orig_timestamp = pc.last_audited
+            sleep 1
+            po_handler.update_version_after_validation
+            expect(pc.reload.last_audited).to be > orig_timestamp
+          end
+          it 'updates PreservedCopy last_checked_on_storage' do
+            orig_timestamp = pc.last_checked_on_storage
```
Comment (jmartin-sul) [inline spec/services/preserved_object_handler_update_version_spec.rb]: same (why no) `sleep` question

File: app/services/preserved_object_handler.rb [hunk 3]
```diff
@@ -163,25 +195,29 @@ def create_db_objects(status, validated=false)
...
       if incoming_version > pres_copy.version && pres_copy.version == pres_object.current_version
         results << result_hash(ARG_VERSION_GREATER_THAN_DB_OBJECT, pres_copy.class.name)
-        update_preserved_copy(pres_copy, incoming_version, incoming_size)
-        results.concat(update_status(pres_copy, Status.ok))
+        update_preserved_copy_version_etc(pres_copy, incoming_version, incoming_size, validated)
+        results.concat(update_status(pres_copy, status)) if status
         results.concat(update_db_object(pres_copy))
         results << result_hash(ARG_VERSION_GREATER_THAN_DB_OBJECT, pres_object.class.name)
-        update_preserved_object(pres_object, incoming_version)
+        pres_object.current_version = incoming_version
```
Comment (jmartin-sul) [inline app/services/preserved_object_handler.rb]: what about also calling `update_pc_validation_timestamps(pres_copy) if validated` here?

File: app/services/preserved_object_handler.rb [hunk 4]
```diff
@@ -163,25 +195,29 @@ def create_db_objects(status, validated=false)
...
     upd_results = with_active_record_transaction_and_rescue do
       pres_object = PreservedObject.find_by!(druid: druid)
-      pres_copy = PreservedCopy.find_by!(preserved_object: pres_object, endpoint: endpoint)
+      pres_copy = PreservedCopy.find_by!(preserved_object: pres_object, endpoint: endpoint) if pres_object
       # FIXME: what if there is more than one associated pres_copy?
       if incoming_version > pres_copy.version && pres_copy.version == pres_object.current_version
         results << result_hash(ARG_VERSION_GREATER_THAN_DB_OBJECT, pres_copy.class.name)
-        update_preserved_copy(pres_copy, incoming_version, incoming_size)
-        results.concat(update_status(pres_copy, Status.ok))
+        update_preserved_copy_version_etc(pres_copy, incoming_version, incoming_size, validated)
```
Comment (SaravShah) [inline app/services/preserved_object_handler.rb]: what does _etc stand for?

File: spec/services/preserved_object_handler_update_version_spec.rb [hunk 5]
```diff
@@ -340,4 +334,370 @@
...
+
+          it 'updates PreservedCopy status to "moab_invalid" if it was "ok"' do
+            pc.status = Status.ok
+            pc.save!
+            po_handler.update_version_after_validation
+            expect(pc.reload.status).to eq Status.invalid_moab
+          end
+        end
+
+        RSpec.shared_examples 'unexpected version with validation' do |incoming_version|
```
Comment (SaravShah) [inline spec/services/preserved_object_handler_update_version_spec.rb]: can this be moved to the `shared_examples_preserved_object_handler.rb` ?

File: app/services/preserved_object_handler.rb [hunk 6]
```diff
@@ -101,22 +101,54 @@ def confirm_version
...
   end
 
-  def update_version
+  def update_version_after_validation
     results = []
     if invalid?
       results << result_hash(INVALID_ARGUMENTS, errors.full_messages)
     else
-      Rails.logger.debug "update_version #{druid} called"
+      Rails.logger.debug "update_version_after_validation #{druid} called"
```
Comment (SaravShah) [inline app/services/preserved_object_handler.rb]: Do we need to know when the method was called in the logs?

File: app/services/preserved_object_handler.rb [hunk 7]
```diff
@@ -101,22 +101,54 @@ def confirm_version
...
       if endpoint.endpoint_type.endpoint_class == 'online'
-        results.concat(update_online_version)
+        upd_results =
+          if moab_validation_errors.empty?
+            with_active_record_transaction_and_rescue do
```
[the remark this answers is not in the document]
Comment (ndushay) [reply app/services/preserved_object_handler.rb]: good point.  I was applying copy pasta without thinking.  Changing.

File: app/services/preserved_object_handler.rb [hunk 8]
```diff
@@ -101,22 +101,54 @@ def confirm_version
...
     results
   end
 
+  def update_version
+    results = []
+    if invalid?
+      results << result_hash(INVALID_ARGUMENTS, errors.full_messages)
+    else
+      Rails.logger.debug "update_version #{druid} called"
+      upd_results = with_active_record_transaction_and_rescue do
```
[the remark this answers is not in the document]
Comment (ndushay) [reply app/services/preserved_object_handler.rb]: i think we'll be fine without transaction wrapping here.  It's a lookup, not an update.  And there is no "else" fall through.  Removing transaction wrapping, captain.

File: app/services/preserved_object_handler.rb (hunk 6 above)
Comment (ndushay) [reply app/services/preserved_object_handler.rb]: yes.  It's a "debug" level message, so it will only be written if logging level is set to "debug"

File: app/services/preserved_object_handler.rb (hunk 4 above)
Comment (ndushay) [reply app/services/preserved_object_handler.rb]: "et cetera" because I couldn't think of a better name for the method.  Open to suggestions.

File: app/services/preserved_object_handler.rb [hunk 9]
```diff
@@ -163,25 +195,29 @@ def create_db_objects(status, validated=false)
...
+        pres_object.current_version = incoming_version
         results.concat(update_db_object(pres_object))
       else
         results << result_hash(UNEXPECTED_VERSION, 'PreservedCopy')
         results.concat(version_comparison_results(pres_copy, :version))
         results.concat(version_comparison_results(pres_object, :current_version))
-        # FIXME: TODO: should it update existence check timestamps/status?
+        results.concat(update_status(pres_copy, status)) if status
+        update_pc_validation_timestamps(pres_copy) if validated
+        results.concat(update_db_object(pres_copy)) if pres_copy.changed?
```
[the remark this answers is not in the document]
Comment (ndushay) [reply app/services/preserved_object_handler.rb]: I took my spec from here:  https://github.com/sul-dlss/preservation_catalog/issues/287  which was from some conversations or other with Julian.  

Did I get it wrong?

File: app/services/preserved_object_handler.rb [hunk 10]
```diff
@@ -234,17 +272,19 @@ def version_comparison_results(db_object, version_symbol)
     results
   end
 
+  # FIXME: this needs to go away in favor of ? update_version_after_validation
+  #  it is only used by confirm_version, which should essentially call
+  #  update_version_after_validation if the incoming_version is higher than the db
+  # One big problem with this is the overwriting of the PC status without validating first
```
[the remark this answers is not in the document]
Comment (ndushay) [reply app/services/preserved_object_handler.rb]: See #353

File: spec/services/preserved_object_handler_update_version_spec.rb [hunk 11]
```diff
@@ -340,4 +334,370 @@
...
+
+        it 'updates PreservedCopy last_audited' do
+          orig_timestamp = pc.last_audited
+          sleep 1
+          po_handler.update_version_after_validation
+          expect(pc.reload.last_audited).to be > orig_timestamp
+        end
+        it 'updates PreservedCopy last_checked_on_storage' do
+          orig_timestamp = pc.last_checked_on_storage
+          po_handler.update_version_after_validation
```
[the remark this answers is not in the document]
Comment (ndushay) [reply spec/services/preserved_object_handler_update_version_spec.rb]: I only put in sleep where the tests failed without it.  I think it has to do with whether the time field has fractions of a second or not.  I can add comments to clarify.

File: spec/services/preserved_object_handler_update_version_spec.rb [hunk 12]
```diff
@@ -340,4 +334,370 @@
...
+            endpoint: ep,
+            status: Status.ok,
+            last_audited: Time.current.to_i,
+            last_checked_on_storage: Time.current
+          )
+        end
+
+        it 'updates PreservedCopy last_audited' do
+          orig_timestamp = pc.last_audited
+          sleep 1
```
Comment (ndushay) [inline spec/services/preserved_object_handler_update_version_spec.rb]: same answer about sleeping in tests.  :-D  (I think I deleted @jmartin-sul 's comment, by accident.)

File: spec/services/preserved_object_handler_update_version_spec.rb [hunk 13]
```diff
@@ -340,4 +334,370 @@
...
+          allow(pc).to receive(:last_audited=)
+          allow(pc).to receive(:last_checked_on_storage=)
+          allow(pc).to receive(:changed?).and_return(false)
+          allow(pc).to receive(:touch)
+          po_handler.update_version_after_validation
+          expect(po).not_to have_received(:touch)
+          expect(pc).not_to have_received(:touch)
+        end
+
+        context 'incoming version newer than catalog versions (both) (happy path)' do
```
[the remark this answers is not in the document]
Comment (ndushay) [reply spec/services/preserved_object_handler_update_version_spec.rb]: good catch!

File: spec/services/preserved_object_handler_update_version_spec.rb (hunk 5 above)
Comment (ndushay) [reply spec/services/preserved_object_handler_update_version_spec.rb]: It is only useful in this one context, so I left it here.  I know these tests are long;  I went with "shameless green".  Happy to entertain ideas for shortening them, etc.

File: spec/services/preserved_object_handler_update_version_spec.rb (hunk 2 above)
Comment (ndushay) [reply spec/services/preserved_object_handler_update_version_spec.rb]: same answer:  last_checked_on_storage is aware of fractions of a second and needs no sleep.  Comments added to sleep lines.

**Comment by ndushay** [comment]
@jmartin-sul @SaravShah  I have added commits to address some of your concerns (and also rebased on master);  I responded to all other comments, I believe.

File: app/services/preserved_object_handler.rb (hunk 3 above)
Comment (jmartin-sul) [reply app/services/preserved_object_handler.rb]: nah, that's fine, i missed that, and similar concerns here, but no suggestions for fixing them jump to mind

File: app/services/preserved_object_handler.rb (hunk 9 above)
[the remark this answers is not in the document]
Comment (jmartin-sul) [reply app/services/preserved_object_handler.rb]: nope, my bad, i think i was just unclear on the expected behavior there

File: app/services/preserved_object_handler.rb (hunk 10 above)
[the remark this answers is not in the document]
Comment (jmartin-sul) [reply app/services/preserved_object_handler.rb]: thanks for filing!

File: app/services/preserved_object_handler.rb (hunk 4 above)
Comment (SaravShah) [reply app/services/preserved_object_handler.rb]: updated_pc_obj
updated_pc_version
updated_pc_db_obj

i dunno just throwing names out there...

Comment (ndushay) [reply app/services/preserved_object_handler.rb]: I was trying to say "this is updating a pc object version, along with some other fields"
